# Development Dockerfile for gateway-service
FROM node:20-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set the working directory to the root of the monorepo
WORKDIR /app

# Dependency Installation 

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY services/gateway-service/package.json ./services/gateway-service/

ENV NODE_ENV=development

RUN pnpm install --ignore-scripts

COPY services/gateway-service ./services/gateway-service/

EXPOSE 3000

CMD ["pnpm", "--filter", "api-gateway-service", "start:dev"]