export const envSchema = {
  type: "object",
  required: [
    "PORT",
    "SMTP_USER",
    "SMTP_PASS",
    "SMTP_HOST",
    "SMTP_PORT",
    "NODE_ENV",
    "SERVICE_NAME",
    "CONSUL_HOST",
    "CONSUL_PORT",
    "RABBITMQ_CONNECTION_URL",
  ],
  properties: {
    PORT: { type: "number", default: 3001 },
    SMTP_USER: { type: "string" },
    SMTP_PASS: { type: "string" },
    SMTP_HOST: { type: "string" },
    SMTP_PORT: { type: "number" },
    RABBITMQ_CONNECTION_URL: { type: "string" },
    SERVICE_NAME: { type: "string" },
    CONSUL_HOST: { type: "string" },
    CONSUL_PORT: { type: "number" },
    NODE_ENV: { type: "string", default: "development" },
  },
}
