# Development Dockerfile for gateway-service
FROM node:20-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set the working directory to the root of the monorepo
WORKDIR /app

# Dependency Installation 

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY services/template-service/package.json ./services/template-service/

ENV NODE_ENV=development

RUN pnpm install --ignore-scripts

COPY services/template-service ./services/template-service/

EXPOSE 3002

CMD ["pnpm", "--filter", "template-service", "dev"]