# Development Dockerfile for gateway-service
FROM node:20-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set the working directory to the root of the monorepo
WORKDIR /app

# Dependency Installation 

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY services/push-service/package.json ./services/push-service/

ENV NODE_ENV=development

RUN pnpm install --ignore-scripts

COPY services/push-service ./services/push-service/

EXPOSE 3003

CMD ["pnpm", "--filter", "push-service", "dev"]