FROM node:20-alpine AS builder

RUN npm install -g pnpm@10.20.0

WORKDIR /app

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
COPY services/user-service/package.json ./services/user-service/
COPY services/user-service ./services/user-service

RUN pnpm install --frozen-lockfile --filter user-service...
RUN pnpm --filter user-service run build


FROM node:20-alpine

RUN npm install -g pnpm@10.20.0

WORKDIR /app

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY services/user-service/package.json ./services/user-service/

RUN pnpm install --prod --frozen-lockfile --filter user-service --ignore-scripts

COPY --from=builder /app/services/user-service/dist ./services/user-service/dist

EXPOSE 3004

CMD ["node", "services/user-service/dist/server.js"]