# Development Dockerfile for gateway-service
FROM node:20-alpine

# Install pnpm globally
RUN npm install -g pnpm

# Set the working directory to the root of the monorepo
WORKDIR /app

# Dependency Installation 

COPY pnpm-workspace.yaml ./
COPY package.json ./
COPY pnpm-lock.yaml ./
COPY services/email-service/package.json ./services/email-service/

ENV NODE_ENV=development

RUN pnpm install --ignore-scripts

COPY services/email-service ./services/email-service/

EXPOSE 3001

CMD pnpm --filter email-service run dev
